######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 19 11:05:29 2014
######################################################################

TEMPLATE = app
TARGET = HiQDock
DEPENDPATH += .
INCLUDEPATH += .

LIBS += -lbe
LIBS += -ltracker

QT += core gui widgets quickwidgets
QT += qml quick
CONFIG += debug
CONFIG += qml_debug


RESOURCES += HiQDock.qrc

# DEFINES += QT_NO_DEBUG_OUTPUT

# Input
HEADERS += mainWindow.h \
           HaikuMouseTrackingView.h \
           HQDDialogWindow.h

SOURCES += main.cpp \
           mainWindow.cpp \
           HQDDialogWindow.cpp \
           HaikuMouseTrackingView.cpp
